---
- name: Create directory.
  file:
    path: "~/backend"
    state: directory

- name: "Move backend files to server."
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "install package dependencies"
  shell: |
    cd ~/home/ubuntu/backend
    pwd
    tar -xzvf artifact.tar.gz -C backend
    rm artifact.tar.gz
    
- name: "run npm audit & run build & start"
  shell: |    
    cd backend/
    npm audit fix
    npm run build
    cd dist
    pm2 start npm --name backend -- start
