---
- name: Create directory.
  file:
    path: "~/backend"
    state: directory

- name: "Move backend files to server."
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/

- name: "install package dependencies"
  shell: |
    cd ~/home/ubuntu/
    tar -xzvf artifact.tar.gz -C backend
    rm artifact.tar.gz
    
- name: "npm run install & start"
  shell: |    
    cd ~/backend/dist
    npm install
    pm2 stop default
    pm2 start npm -- start
