---

- name: "Move backend files to server."
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu

- name: "install package dependencies"
  shell: |
    cd /home/ubuntu
    tar -xzvf artifact.tar.gz -C backend
    rm artifact.tar.gz
    cd backend/
    npm audit fix
    npm run build
    cd dist
    pm2 start npm --name backend -- start
